name: first_tuto
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  battery_plus: ^6.0.1
  device_info_plus: ^10.0.0
  cupertino_icons: ^1.0.8
  flutter_blue_plus: ^1.31.0
  permission_handler: ^11.3.1
  app_settings: ^6.1.1
  fl_chart: ^0.65.0
  flutter_launcher_icons: ^0.14.4
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#0B1020"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
